# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Bugbear'
    organization: '210215-usf-net'
    scannerMode: 'MSBuild'
    projectKey: '210215-USF-NET_Bugbear-By-TeamPomodoro-Angular'
    projectName: 'Bugbear-By-TeamPomodoro-Angular'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng run build --prod
  displayName: 'npm install and build'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (1f0ad125-9c6d-4dd3-a0e2-6bf5052dffe8)'
    appType: 'webApp'
    WebAppName: 'bugbearcampaignmanager'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'